### ISSUE TITLE
iOS 6 Bug

### ISSUE THREAD

**Issue by guero235** [ednasgoldfishuk/CDVPluginTwitter#2]
After calling "isTwitterAvailable", the app will freeze when resumed on  iOS 6.  It seems there is an issue when TWTweetComposeViewController is initialized but never used.  You should release the controller after you check if it is null as seen here:

http://brianistech.wordpress.com/2011/10/13/ios-5-twitter-integration/

**Comment by ednasgoldfishuk** [comment]
Thanks, just added in
